title: Anthony Williams CEAMLS SAIRI Website Summer 2024 
logo: assets/img/best-coding-language-for-games.jpg
description: Hi! My name is Anthony Williams and this is my CEAMLS SAIRI Website for Summer 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
